name: Clase 02 YAML y Workflows 

on: push

jobs: 
  first_job: # Si algún job falla, el workflow se detiene.
    runs-on: ubuntu-latest
    env:
      NAME: "Pool Llerena"
    steps:
      - name: Hola mundo
        run: echo Hola mundo, $NAME

      - name: Otra forma de acceder a las variables de entorno
        run: echo "Hola mundo, ${{ env.NAME }}"

  second_job:
    if: ${{ github.ref == 'refs/heads/main' }} # Este job solo se ejecuta si el push es a la rama main.
    needs: first_job
    runs-on: ubuntu-latest
    steps:
      - name: Adiós mundo
        run: echo "Adiós mundo"
    
  third_job:
    name: Descargar el repositorio
    runs-on: ubuntu-latest
    steps:
      - name: Listar archivos antes de descargar el repositorio
        shell: bash # Define el shell a usar
        run: ls -la
        
      - name: Descargar el repositorio
        uses: actions/checkout@v4

      - name: Listar archivos después de descargar el repositorio
        run: ls -la

  # Outputs a nivel de job (reutilizable en los steps del mismo job)
  fourth_job:
    name: Utilizando Outputs a nivel de job
    runs-on: ubuntu-latest
    steps:
      - name: Definir un output para reutilizar
        id: step_1
        run: echo "my_variable=Hola mundo" >> $GITHUB_OUTPUT

      - name: Obtener el output
        run: 'echo "El valor del step_1 es: ${{ steps.step_1.outputs.my_variable }}"'

  # Outputs a nivel de workflow (reutilizable en otros jobs)
  fifth_job:
    name: Utilizando Outputs a nivel de workflow
    runs-on: ubuntu-latest
    outputs:
      my_output: ${{ steps.step_1.outputs.my_variable }}
    steps:
      - name: Definir un output para reutilizar
        id: step_1
        run: echo "my_variable=Hola mundo desde el output del workflow" >> $GITHUB_OUTPUT
    
  sixth_job:
    name: Acceder a Outputs de otros jobs
    runs-on: ubuntu-latest
    needs: fifth_job # Necesita fifh_job se complete antes de ejecutarse.
    steps:
      - name: Acceder al output del job fifth_job
        run: 'echo "El valor del output del job fifth_job es: ${{ needs.fifth_job.outputs.my_output }}"'