name: Clase 02 YAML y Workflows 

on: push

jobs: 
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Hola mundo
        run: echo "Hola mundo"
  
  second_job:
    if: ${{ github.ref == 'refs/heads/main' }} # Este job solo se ejecuta si el push es a la rama main.
    needs: first_job
    runs-on: ubuntu-latest
    steps:
      - name: Adiós mundo
        run: echo "Adiós mundo"