name: Clase 02 YAML y Workflows 

on: push

jobs: 
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Hola mundo
        run: echo "Hola mundo"
  
  second_job:
    runs-on: ubuntu-latest
    steps:
      - name: Adiós mundo
        run: echo "Adiós mundo"