name: Clase 02 YAML y Workflows 

on: push

jobs: 
  first_job: # Si algún job falla, el workflow se detiene.
    runs-on: ubuntu-latest
    env:
      NAME: "Pool Llerena"
    steps:
      - name: Hola mundo
        run: echo Hola mundo, $NAME

      - name: Otra forma de acceder a las variables de entorno
        run: echo "Hola mundo, ${{ env.NAME }}"

  second_job:
    if: ${{ github.ref == 'refs/heads/main' }} # Este job solo se ejecuta si el push es a la rama main.
    needs: first_job
    runs-on: ubuntu-latest
    steps:
      - name: Adiós mundo
        run: echo "Adiós mundo"